# General
seed: 1
device: "cuda:0"
debug: True # For logging

# Dir
exp_name: "default"
output_dir: "ddim-inversion/${exp_name}"

# Data
data_dir: "<your_path>/data"
src_video_path: "${data_dir}/woman-running.mp4" #Override it with video_path
image_size: [512, 512]
save_video_frames: False

# Model
model_name: "seine"
sd_path: "./pretrained/stable-diffusion-v1-4"
ckpt_path: "./pretrained/SEINE/seine.pt"
model_key: "./pretrained/stable-diffusion-v1-4"
enable_xformers_memory_efficient_attention: True
use_fp16: True

# Schedular
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"

# DDIM inversion
n_steps: 500
n_save_steps: 250
n_frame_to_invert: 16
inversion_prompt: ""
batch_size: 1  # TODO: batchsize is always 1 for inversion, we can remove this